export class SupabaseConfig {
  static readonly PROJECT_URL: string = 'https://idgiijblubzmllwfypsw.supabase.co';
  static readonly ANON_KEY: string =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkZ2lpamJsdWJ6bWxsd2Z5cHN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY5NDY0ODIsImV4cCI6MjEwMjUyMjQ4Mn0.QUoR07ssQYYxR65NV9dU_49G36DoLFl_hAu3uV4aigc';
  static readonly STORAGE_BUCKET: string = 'images';
}
